name: SKY UX CI

on:
  pull_request:
  push:
    branches:
      - master
      - 3.x.x

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: Blackbaud-SteveBrush/skyux-libraries-action@v1.0.0-alpha.9
        with:
          browser-stack-access-key: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          browser-stack-username: ${{ secrets.BROWSER_STACK_USERNAME }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          personal-access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
